services:
  ridngo-frontend:
    image: "${APP_IMAGE:?APP_IMAGE requis}"
    container_name: ridngo-frontend
    pull_policy: always
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/ >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 15
      start_period: 40s
    logging: { driver: "json-file", options: { max-size: "50m", max-file: "5" } }
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ridngo-front.rule=Host(`ridngo.yowyob.com`)"
      - "traefik.http.routers.ridngo-front.entrypoints=websecure"
      - "traefik.http.routers.ridngo-front.tls=true"
      - "traefik.http.routers.ridngo-front.tls.certresolver=letsencrypt"
      - "traefik.http.routers.ridngo-front.priority=10"
      - "traefik.http.services.ridngo-front.loadbalancer.server.port=3000"
      - "traefik.docker.network=yowyob"
    networks: [yowyob]
networks:
  yowyob: { external: true, name: yowyob }
